version: "3.8"

services:
  bp-ai-engine:
    container_name: bp-ai-engine
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env  # This will load all variables from .env file
    environment:
      - LOG_FILE=/app/logs/app.log